leftnav:
- identifier: 5af2aa71-9c80-4dbb-bdb2-069dc17d10a2
  name: page
  url: /pages/site01-page
  weight: 10
- identifier: 7760f366-6b3a-4ec0-aee4-6378ecfedd2c
  name: link
  url: /resources/image32
  weight: 20
